// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type AllResponseBlackList struct {
	Error bool         `json:"error"`
	Data  []*BlackList `json:"data"`
	Code  int          `json:"code"`
	Msg   string       `json:"msg"`
	Type  string       `json:"type"`
}

type BlackList struct {
	ID          int       `json:"id"`
	Description string    `json:"description"`
	CreatedAt   time.Time `json:"created_at"`
}

type NewBlackList struct {
	ID          int    `json:"id"`
	Description string `json:"description"`
}

type RequestNewBlackList struct {
	Data *NewBlackList `json:"data"`
}

type RequestUpdateBlackList struct {
	Data *UpdateBlackList `json:"data"`
}

type ResponseBlackList struct {
	Error bool       `json:"error"`
	Data  *BlackList `json:"data"`
	Code  int        `json:"code"`
	Msg   string     `json:"msg"`
	Type  string     `json:"type"`
}

type UpdateBlackList struct {
	ID          int    `json:"id"`
	Description string `json:"description"`
}
